<?php

class My_Faq_Model_Resource_Mfaq_Collection extends Mage_Core_Model_Mysql4_Collection_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('faq/mfaq');
    }
}
