<?php

/*class My_FAQ_Block_Adminhtml_FAQ extends Mage_Adminhtml_Block_Widget_Grid_Container
{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $helper = Mage::helper('faq');
        $this->_blockGroup = 'my_faq_block';
        $this->_controller = 'adminhtml_faq';
        $this->_headerText = $helper->__('FAQ Managment');
        $this->_addButtonLabel = $helper->__('Add FAQ');
    }
}*/

class My_FAQ_Adminhtml_FAQController extends Mage_Adminhtml_Controller_Action
{
    public function myactionAction()
    {
        die('admin');
    }
}