<?php

class My_FAQ_Model_Resource_FAQ_Collection extends Mage_Core_Model_Mysql4_Collection_Abstract
{
    function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('myfaq/faq');
    }
}