<?php

class My_Faq_Model_Mfaq extends Mage_Core_Model_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('faq/mfaq');
    }
}
